
--What is the total revenue generated by male vs. female customers?
SELECT gender, SUM("purchase_amount_(usd)") as revenue
from customer
GROUP BY gender

--which customer used a discount but stil spent more than the average purchase amount?
SELECT customer_id, "purchase_amount_(usd)"
FROM customer
WHERE discount_applied = 'Yes' AND "purchase_amount_(usd)" >= (SELECT AVG("purchase_amount_(usd)") FROM customer)